# Generated by Django 5.2.9 on 2026-03-24 03:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=16, verbose_name='作者')),
                ('news_link', models.URLField(verbose_name='文章链接')),
                ('release_time', models.DateTimeField(verbose_name='发布时间')),
                ('add_time', models.DateTimeField(verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '金融新闻',
                'verbose_name_plural': '金融新闻',
            },
        ),
    ]
