# Generated by Django 5.2.9 on 2026-03-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financenews',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
    ]
