# Generated by Django 5.2.9 on 2026-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_financenews_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financenews',
            name='author',
            field=models.CharField(max_length=255, verbose_name='作者'),
        ),
    ]
