# Generated by Django 5.2.9 on 2025-12-09 08:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('real_name', models.CharField(max_length=16, verbose_name='真实姓名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('is_vip', models.BooleanField(default=False, verbose_name='是否为会员')),
                ('vip_end_time', models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('register_ip', models.CharField(max_length=16, verbose_name='注册IP')),
                ('last_login_ip', models.CharField(max_length=16, verbose_name='上次登陆IP')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='上次登陆时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否注销')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='注销时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
