# Generated by Django 5.2.9 on 2026-06-01 13:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系方式')),
                ('email', models.CharField(max_length=40, verbose_name='电子邮箱')),
                ('content', models.TextField(verbose_name='合作意向描述')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('is_connect', models.BooleanField(default=False, verbose_name='是否已联系')),
                ('connect_time', models.DateTimeField(blank=True, null=True, verbose_name='联系时间')),
                ('connect_result', models.TextField(blank=True, null=True, verbose_name='联系结果(备注)')),
            ],
            options={
                'verbose_name': '合作申请记录',
                'verbose_name_plural': '合作申请记录',
            },
        ),
        migrations.CreateModel(
            name='EmailSub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('is_sub', models.BooleanField(default=False, verbose_name='是否订阅')),
                ('del_time', models.DateTimeField(blank=True, null=True, verbose_name='取消订阅时间')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订阅邮箱',
                'verbose_name_plural': '订阅邮箱',
            },
        ),
        migrations.CreateModel(
            name='GameSymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='产品名')),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品别名')),
                ('is_game', models.BooleanField(default=False, verbose_name='是否可竞猜')),
            ],
            options={
                'verbose_name': '竞猜产品',
                'verbose_name_plural': '竞猜产品',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='StudyContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.IntegerField(blank=True, choices=[(1, '审核中'), (2, '审核未通过'), (3, '审核通过')], default=1, null=True, verbose_name='文章状态')),
                ('cover_image_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='封面图片壁纸')),
            ],
            options={
                'verbose_name': '学习中心文章',
                'verbose_name_plural': '学习中心文章',
            },
        ),
        migrations.CreateModel(
            name='UserActiveAndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '代理用户关系表',
                'verbose_name_plural': '代理用户关系表',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=16, verbose_name='手机号')),
                ('real_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='真实姓名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('is_vip', models.BooleanField(default=False, verbose_name='是否为会员')),
                ('vip_end_time', models.DateTimeField(blank=True, null=True, verbose_name='会员到期时间')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('register_ip', models.CharField(max_length=16, verbose_name='注册IP')),
                ('last_login_ip', models.CharField(max_length=16, verbose_name='上次登陆IP')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='上次登陆时间')),
                ('is_receive_vip', models.BooleanField(default=False, verbose_name='是否已领取新手VIP')),
                ('is_vip_experience', models.BooleanField(default=False, verbose_name='是否为体验VIP用户')),
                ('point', models.IntegerField(default=0, verbose_name='积分')),
                ('point_level', models.IntegerField(choices=[(1, '交易萌新'), (2, '市场学徒'), (3, '市场新锐'), (4, '策略新手'), (5, '策略学徒'), (6, '图表猎人'), (7, '趋势捕手'), (8, '资金魔术师'), (9, '市场先知'), (10, '交易指挥官')], default=1, verbose_name='积分等级')),
                ('user_stutas', models.IntegerField(choices=[(1, '正常'), (2, '封禁'), (3, '冻结')], default=1, verbose_name='用户状态')),
                ('is_first_pay', models.BooleanField(default=True, verbose_name='是否已充值')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否注销')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否为代理')),
                ('active_code', models.CharField(max_length=16, null=True, verbose_name='代理代码')),
                ('active_level', models.IntegerField(default=1, verbose_name='代理等级')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='注销时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='GameCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_date', models.DateTimeField(verbose_name='交易日')),
                ('start_time', models.DateTimeField(verbose_name='开始日')),
                ('end_time', models.DateTimeField(verbose_name='结算日')),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当日开盘价')),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当日收盘价')),
                ('result', models.IntegerField(blank=True, choices=[(1, 'up'), (2, 'down')], null=True, verbose_name='当日结果')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gamesymbol', verbose_name='竞猜产品')),
            ],
            options={
                'verbose_name': '竞猜交易日',
                'verbose_name_plural': '竞猜交易日',
            },
        ),
        migrations.CreateModel(
            name='StudyComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('comment', models.CharField(max_length=4000, verbose_name='评论内容')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('study_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studycontent', verbose_name='被评论文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '用户评论记录',
                'verbose_name_plural': '用户评论记录',
            },
        ),
        migrations.CreateModel(
            name='UserActiveWalletLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='冻结金额')),
                ('thaw_time', models.DateTimeField(verbose_name='解冻时间')),
                ('is_thaw', models.BooleanField(default=False, verbose_name='是否解冻')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useractiveanduser')),
            ],
            options={
                'verbose_name': '代理冻结金额记录',
                'verbose_name_plural': '代理冻结金额记录',
            },
        ),
        migrations.CreateModel(
            name='UserGameSignUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='竞猜积分')),
                ('guess', models.IntegerField(choices=[(1, 'up'), (2, 'down')], verbose_name='竞猜方向')),
                ('result', models.IntegerField(blank=True, choices=[(1, 'win'), (2, 'lose')], null=True, verbose_name='竞猜结果')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='竞猜时间')),
                ('is_end', models.BooleanField(default=False, verbose_name='是否结算')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
                ('game_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gamecenter', verbose_name='竞猜交易日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '竞猜报名记录',
                'verbose_name_plural': '竞猜报名记录',
            },
        ),
        migrations.CreateModel(
            name='UserActiveWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('freeze', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='冻结余额')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name': '代理钱包余额',
                'verbose_name_plural': '代理钱包余额',
            },
        ),
        migrations.AddField(
            model_name='useractiveanduser',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='useractiveanduser',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='users.userprofile'),
        ),
        migrations.CreateModel(
            name='StudyGood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否取消')),
                ('study_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studycontent', verbose_name='被点赞文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '用户点赞记录',
                'verbose_name_plural': '用户点赞记录',
            },
        ),
        migrations.AddField(
            model_name='studycontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='作者'),
        ),
        migrations.CreateModel(
            name='StudyCommentGood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞评论时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否取消')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studycomment', verbose_name='被点赞评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='点赞评论用户')),
            ],
            options={
                'verbose_name': '用户评论点赞记录',
                'verbose_name_plural': '用户评论点赞记录',
            },
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='变化前积分')),
                ('add_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='变化积分')),
                ('new_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='变化后积分')),
                ('change_oper', models.IntegerField(blank=True, choices=[(1, '报名竞猜'), (2, '竞猜获胜'), (3, '会员赠送'), (4, '注册赠送'), (5, '系统赠送')], null=True, verbose_name='变动类型')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分变动记录',
                'verbose_name_plural': '积分变动记录',
            },
        ),
        migrations.CreateModel(
            name='UserWalletExtract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='提取金额')),
                ('is_with', models.BooleanField(default=False, verbose_name='是否处理')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否取消')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useractivewallet')),
            ],
            options={
                'verbose_name': '代理提取纪录',
                'verbose_name_plural': '代理提取纪录',
            },
        ),
    ]
