# Generated by Django 5.2.9 on 2026-03-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                        verbose_name="性别",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(
                default="", max_length=254, null=True, verbose_name="邮箱"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_vip_experience",
            field=models.BooleanField(default=False, verbose_name="是否为体验VIP用户"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="point",
            field=models.IntegerField(default=0, verbose_name="积分"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="point_level",
            field=models.IntegerField(
                choices=[
                    (1, "交易萌新"),
                    (2, "市场学徒"),
                    (3, "市场新锐"),
                    (4, "策略新手"),
                    (5, "策略学徒"),
                    (6, "图表猎人"),
                    (7, "趋势捕手"),
                    (8, "资金魔术师"),
                    (9, "市场先知"),
                    (10, "交易指挥官"),
                ],
                default=1,
                verbose_name="积分等级",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_stutas",
            field=models.IntegerField(
                choices=[(1, "正常"), (2, "封禁"), (3, "冻结")],
                default=1,
                verbose_name="用户状态",
            ),
        ),
    ]
