# Generated by Django 5.2.9 on 2026-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_receive_vip',
            field=models.BooleanField(default=False, verbose_name='是否已领取新手VIP'),
        ),
    ]
