# Generated by Django 5.2.9 on 2026-03-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_receive_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='真实姓名'),
        ),
    ]
