# Generated by Django 5.2.9 on 2026-03-26 05:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_email_alter_userprofile_real_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='产品名')),
                ('is_game', models.BooleanField(default=False, verbose_name='是否可竞猜')),
            ],
            options={
                'verbose_name': '竞猜产品',
                'verbose_name_plural': '竞猜产品',
            },
        ),
        migrations.CreateModel(
            name='GameCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_date', models.DateField(verbose_name='交易日')),
                ('strat_time', models.DateTimeField(verbose_name='开始日')),
                ('end_time', models.DateTimeField(verbose_name='结算日')),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当日开盘价')),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='当日收盘价')),
                ('result', models.IntegerField(choices=[(1, 'up'), (2, 'down')], verbose_name='当日结果')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gamesymbol', verbose_name='竞猜产品')),
            ],
            options={
                'verbose_name': '竞猜交易日',
                'verbose_name_plural': '竞猜交易日',
            },
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='变化前积分')),
                ('add_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='变化积分')),
                ('new_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='变化后积分')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分变动记录',
                'verbose_name_plural': '积分变动记录',
            },
        ),
        migrations.CreateModel(
            name='UserGameSignUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='竞猜积分')),
                ('guess', models.IntegerField(choices=[(1, 'up'), (2, 'down')], verbose_name='竞猜方向')),
                ('result', models.IntegerField(choices=[(1, 'win'), (2, 'lose')], verbose_name='竞猜结果')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='竞猜时间')),
                ('is_end', models.BooleanField(default=False, verbose_name='是否结算')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结算时间')),
                ('game_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.gamecenter', verbose_name='竞猜交易日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '竞猜报名记录',
                'verbose_name_plural': '竞猜报名记录',
            },
        ),
    ]
