# Generated by Django 5.2.9 on 2026-03-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_gamesymbol_gamecenter_pointrecord_usergamesignup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecenter',
            old_name='strat_time',
            new_name='start_time',
        ),
    ]
