# Generated by Django 5.2.9 on 2026-03-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_gamecenter_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecenter',
            name='game_date',
            field=models.DateTimeField(verbose_name='交易日'),
        ),
    ]
