# Generated by Django 5.2.9 on 2026-03-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_gamecenter_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesymbol',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='产品别名'),
        ),
    ]
