# Generated by Django 5.2.9 on 2026-03-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usergamesignup_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrecord',
            name='change_oper',
            field=models.IntegerField(blank=True, choices=[(1, '报名竞猜'), (2, '竞猜获胜'), (3, '会员赠送'), (4, '注册赠送'), (5, '系统赠送')], null=True, verbose_name='变动类型'),
        ),
    ]
