# Generated by Django 5.2.9 on 2026-03-30 16:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pointrecord_change_oper'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.IntegerField(blank=True, choices=[(1, '审核中'), (2, '审核未通过'), (3, '审核通过')], default=1, null=True, verbose_name='文章状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='作者')),
            ],
            options={
                'verbose_name': '学习中心文章',
                'verbose_name_plural': '学习中心文章',
            },
        ),
    ]
