# Generated by Django 5.2.9 on 2026-03-30 16:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_studycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycontent',
            name='cover_image_path',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='封面图片壁纸'),
        ),
        migrations.CreateModel(
            name='StudyComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('comment', models.CharField(max_length=4000, verbose_name='评论内容')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('study_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studycontent', verbose_name='被评论文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '用户评论记录',
                'verbose_name_plural': '用户评论记录',
            },
        ),
        migrations.CreateModel(
            name='StudyGood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否取消')),
                ('study_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studycontent', verbose_name='被点赞文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '用户点赞记录',
                'verbose_name_plural': '用户点赞记录',
            },
        ),
    ]
