# Generated by Django 5.2.9 on 2026-03-31 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_studycontent_cover_image_path_studycomment_studygood'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCommentGood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='点赞评论时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否取消')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studycomment', verbose_name='被点赞评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='点赞评论用户')),
            ],
            options={
                'verbose_name': '用户评论点赞记录',
                'verbose_name_plural': '用户评论点赞记录',
            },
        ),
    ]
