# Generated by Django 5.2.9 on 2026-04-08 15:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_studycommentgood'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系方式')),
                ('email', models.CharField(max_length=40, verbose_name='电子邮箱')),
                ('content', models.TextField(verbose_name='合作意向描述')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间')),
                ('is_connect', models.BooleanField(default=False, verbose_name='是否已联系')),
                ('connect_time', models.DateTimeField(blank=True, null=True, verbose_name='联系时间')),
                ('connect_result', models.TextField(blank=True, null=True, verbose_name='联系结果(备注)')),
            ],
            options={
                'verbose_name': '合作申请记录',
                'verbose_name_plural': '合作申请记录',
            },
        ),
        migrations.CreateModel(
            name='EmailSub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, verbose_name='邮箱')),
                ('is_sub', models.BooleanField(default=False, verbose_name='是否订阅')),
                ('del_time', models.DateTimeField(blank=True, null=True, verbose_name='取消订阅时间')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订阅邮箱',
                'verbose_name_plural': '订阅邮箱',
            },
        ),
    ]
