# Generated by Django 5.2.9 on 2026-05-12 11:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_agencyapplication_emailsub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_code',
            field=models.CharField(max_length=16, null=True, verbose_name='代理代码'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_level',
            field=models.IntegerField(default=1, verbose_name='代理等级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否为代理'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_first_pay',
            field=models.BooleanField(default=True, verbose_name='是否已充值'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='用户名'),
        ),
        migrations.CreateModel(
            name='UserActiveAndUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='users.userprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='users.userprofile')),
            ],
            options={
                'verbose_name': '代理用户关系表',
                'verbose_name_plural': '代理用户关系表',
            },
        ),
        migrations.CreateModel(
            name='UserActiveWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('freeze', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='冻结余额')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name': '代理钱包余额',
                'verbose_name_plural': '代理钱包余额',
            },
        ),
        migrations.CreateModel(
            name='UserActiveWalletLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='冻结金额')),
                ('thaw_time', models.DateTimeField(verbose_name='解冻时间')),
                ('is_thaw', models.BooleanField(default=False, verbose_name='是否解冻')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useractiveanduser')),
            ],
            options={
                'verbose_name': '代理冻结金额记录',
                'verbose_name_plural': '代理冻结金额记录',
            },
        ),
    ]
