# Generated by Django 5.2.9 on 2026-05-15 13:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_active_code_userprofile_active_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWalletExtract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='提取金额')),
                ('is_with', models.BooleanField(default=False, verbose_name='是否处理')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.useractivewallet')),
            ],
            options={
                'verbose_name': '代理提取纪录',
                'verbose_name_plural': '代理提取纪录',
            },
        ),
    ]
