# Generated by Django 5.2.9 on 2026-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userwalletextract'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwalletextract',
            name='delete_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='userwalletextract',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否取消'),
        ),
    ]
