# Generated by Django 5.2.9 on 2026-06-01 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunPaySymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='充值金额')),
                ('name', models.CharField(max_length=100, verbose_name='产品名')),
                ('subject', models.CharField(default='四川智链数科VIP充值', max_length=100, verbose_name='主题')),
                ('body', models.CharField(max_length=100, verbose_name='产品详情')),
                ('point', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='赠送积分')),
                ('add_vip_time', models.IntegerField(blank=True, null=True, verbose_name='会员增加时长')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否下架')),
            ],
            options={
                'verbose_name': '允许交易alipay产品',
                'verbose_name_plural': '允许交易alipay产品',
            },
        ),
        migrations.CreateModel(
            name='AliPaymentOrder',
            fields=[
                ('orderid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alipay_trade_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付宝交易号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('subject', models.CharField(max_length=256, verbose_name='订单标题')),
                ('body', models.TextField(blank=True, verbose_name='订单描述')),
                ('usd_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单金额(USD)')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunded', '已退款'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='支付状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('add_vip_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='充值会员时长')),
                ('point', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='充值积分赠送')),
                ('notify_time', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('notify_data', models.JSONField(default=dict, verbose_name='通知数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'aliyun',
                'verbose_name_plural': 'aliyun',
                'ordering': ['-created_at'],
            },
        ),
    ]
