# Generated by Django 5.2.9 on 2026-01-08 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliPaymentOrder',
            fields=[
                ('orderid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alipay_trade_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='支付宝交易号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('subject', models.CharField(max_length=256, verbose_name='订单标题')),
                ('body', models.TextField(blank=True, verbose_name='订单描述')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunded', '已退款'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='支付状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('notify_time', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('notify_data', models.JSONField(default=dict, verbose_name='通知数据')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'aliyun',
                'verbose_name_plural': 'aliyun',
                'ordering': ['-created_at'],
            },
        ),
    ]
