# Generated by Django 5.2.9 on 2026-01-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaymentorder',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='充值积分赠送'),
        ),
    ]
