# Generated by Django 5.2.9 on 2026-01-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_pay', '0002_alipaymentorder_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaymentorder',
            name='usd_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单金额(USD)'),
        ),
    ]
