# Generated by Django 5.2.9 on 2026-01-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_pay', '0003_alipaymentorder_usd_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaymentorder',
            name='add_vip_time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='充值会员时长'),
        ),
    ]
