# Generated by Django 5.2.9 on 2026-04-09 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun_pay', '0004_alipaymentorder_add_vip_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunPaySymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='充值金额')),
                ('name', models.CharField(max_length=100, verbose_name='产品名')),
                ('subject', models.CharField(default='四川智链数科VIP充值', max_length=100, verbose_name='主题')),
                ('body', models.CharField(max_length=100, verbose_name='产品详情')),
                ('point', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='赠送积分')),
                ('add_vip_time', models.IntegerField(blank=True, null=True, verbose_name='会员增加时长')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否下架')),
            ],
            options={
                'verbose_name': '允许交易alipay产品',
                'verbose_name_plural': '允许交易alipay产品',
            },
        ),
    ]
