# Generated by Django 5.2.9 on 2026-04-14 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolHistoryPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=255, verbose_name='产品名称')),
                ('open', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='开盘价')),
                ('close', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='收盘价')),
                ('high', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='最低价')),
                ('ticket', models.DateField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '产品历史价格',
                'verbose_name_plural': '产品历史价格',
            },
        ),
    ]
