# Generated by Django 5.2.9 on 2026-04-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolhistoryprice',
            name='ticket',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
