"""
Django settings for MttmView project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ

from pathlib import Path
from utils.DBMysql import DATABASES
import os

import warnings
warnings.filterwarnings('ignore', category=RuntimeWarning, module='django.db.models.fields')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-har^gu6u)_#58hx(vcl2i%m09^w7ef_4$5b4ff5+sn*^vv$qz5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if DEBUG:
    secure = False
    httponly = False
else:
    secure = True
    httponly = True

ALLOWED_HOSTS = ["*"]

# Redis配置
REDIS_HOST = env.str('REDIS_HOST', default="47.108.213.197")
REDIS_PORT = env.str('REDIS_PORT', default=6379)
REDIS_PASSWORD = env.str('REDIS_PASSWORD', default='Qiuqi1201.')
# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.users',
    'apps.kline',
    'apps.aliyun_pay',
    'apps.news',
    'corsheaders',
    'channels'
]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "utils.middleware.DisableCSRFMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CORS 配置，允许所有来源跨域（开发环境建议，生产环境请限制来源）
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True  # ✅ 添加这一行，允许携带 cookie
# 如需允许携带 cookie，可加：CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'MttmView.urls'

# 模板配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 模板目录列表
        'DIRS': [
            BASE_DIR / 'templates',  # 项目级模板目录
            # BASE_DIR / 'theme' / 'templates',  # 可以添加更多目录
        ],
        # 是否在已安装应用中查找模板
        'APP_DIRS': True,  # 设置为 True，让 Django 在每个应用的 templates 目录中查找模板
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 可以添加自定义上下文处理器
                # 'myapp.context_processors.site_settings',
            ],
            'libraries': {
                # 可以注册自定义模板标签
                # 'my_tags': 'myapp.templatetags.my_tags',
            },
            'builtins': [
                # 内置模板标签
                # 'django.templatetags.static',
            ],
        },
    },
]
WSGI_APPLICATION = 'MttmView.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 语言代码：简体中文
LANGUAGE_CODE = 'zh-hans'  # 简体中文

# 时区：中国时区
TIME_ZONE = 'Asia/Shanghai'  # 亚洲/上海

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# 生产环境：收集静态文件的目标目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 重要：必须配置

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

now_url = "http://127.0.0.1:8000"

# 短信功能密钥
AccessKeyId = env.str('AccessKeyId', default='x')
AccessKeySecret = env.str('AccessKeySecret', default='P')
# 支付宝配置

AppPrivateKey = env.str("AppPrivateKey","1")

AppPublicKey = env.str('AppPublicKey', default="2")


AlipayPublicKey = env.str('AlipayPublicKey', default="1")

APPID = env.str('APPID', default='94')

AppNotifyUrl = env.str('AppNotifyUrl', default='https://my.zlsk.me/api/aliyun_pay/call_back/')

ReturnUrl = env.str('ReturnUrl', default='https://my.zlsk.me/api/aliyun_pay/payment_result/')

NotifyUrl = env.str('NotifyUrl', default='https://my.zlsk.me/api/aliyun_pay/alipay_notify/')

PayUrl = env.str("AliPayUrl", "https://openapi-sandbox.dl.alipaydev.com/gateway.do?")

# werbsocket
ASGI_APPLICATION = "MttmView.routing.application"

# Channel Layer 配置
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                # "address": "redis://:your_redis_password@localhost:6379/0",
                "address": f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"
            }],
        },
    },
}

